baseURL = "http://ravness.netlify.com"
languageCode = "jp"
title = "Aimless Blog"
theme="kiss"

hasCJKLanguage = true
enableInlineShortcodes = false
pygmentsUseclasses = false
pygmentsCodeFences = true
copyright = "&copy; <a href=\"https://ravness.com/\">ravness.com</a> 2019"

[blackfriday]
hrefTargetBlank = true

googleAnalytics = ""
Paginate = 5
summaryLength = 70

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Aimless Blog" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks

[params.assets]
customCSS = ["css/custom.css"]

[taxonomies]
tag ="tags"
categories = "categories"

[permalinks]
post = "/:year/:month/:slug/"

[params.sections_left]
"/tags/" = "Tags"
"/categories/" = "Categories"


[params.social]
twitter = ""
github = "Squigly77"
email = ""
tumblr = "lollapal00za"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","tumblr","rss"]


