baseURL = "https://ravness.com"
languageCode = "jp"
title = "Aimless Blog"
theme="kiss"

hasCJKLanguage = true
enableInlineShortcodes = false
copyright = "&copy; <a href=\"https://ravness.com/\">ravness.com</a> 2020"
enableRobotsTXT = true

googleAnalytics = "UA-67464867-3"
Paginate = 5
summaryLength = 70

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "9772961045289102" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Aimless Blog" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = false # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count


[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss

[permalinks]
# post = "/:year/:month/:slug/"
post = "/posts/:slug"

[taxonomies]
tag = "tags"

[params.sections_left]
"/tags/" = "Tags"

[params.social]
twitter = ""
github = "Squigly77"
email = ""
rss = "index.xml" # Add this to show RSS button in social.
tumblr = "lollapal00za.tumblr.com"



[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","rss","tumblr"]

[params]
addThis = "ra-5b3b6c6367750cca"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.blackFriday]
   hrefTargetBlank = true

  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4



