backend:
  name: github
  repo: Squigly77/aimlessblog_hugo
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: title
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Category", name: "categories", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "adsenseTop", name: "related_post", widget: "string", required: false}
      - {label: "adsenseBottom", name: "adsenseBottom", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
